TOP=..
include $(TOP)/configure/CONFIG
#----------------------------------------
#   ADD MACRO DEFINITIONS AFTER THIS LINE
#========================================

# The files in this directory were manually copied from the QHY SDK directories
# for Linux.

# ifneq (, $(filter $(OS_CLASS), Linux))
INC += qhyccd.h
INC += qhyccderr.h
INC += qhyccdcamdef.h
INC += qhyccdstruct.h
INC += config.h
# endif

# Installs version 24.1.9.12
LIB_INSTALLS_Linux += ../os/linux-x86_64/v24.1.9.12/libqhyccd.so.24.1.9.12
LIB_INSTALLS_Linux += ../os/linux-x86_64/v24.1.9.12/libqhyccd.so.20
LIB_INSTALLS_Linux += ../os/linux-x86_64/v24.1.9.12/libqhyccd.so

# Installs version 21.8.26.16
# LIB_INSTALLS_Linux += ../os/linux-x86_64/v21.8.26.16/libqhyccd.so.21.8.26.16
# LIB_INSTALLS_Linux += ../os/linux-x86_64/v21.8.26.16/libqhyccd.so.20
# LIB_INSTALLS_Linux += ../os/linux-x86_64/v21.8.26.16/libqhyccd.so

# Installs version 21.3.13.16
# LIB_INSTALLS_Linux += ../os/linux-x86_64/v21.3.13.16/libqhyccd.so.21.3.13.16
# LIB_INSTALLS_Linux += ../os/linux-x86_64/v21.3.13.16/libqhyccd.so.20
# LIB_INSTALLS_Linux += ../os/linux-x86_64/v21.3.13.16/libqhyccd.so


#==============================
include $(TOP)/configure/RULES