TOP=..
include $(TOP)/configure/CONFIG
#----------------------------------------
#   ADD MACRO DEFINITIONS AFTER THIS LINE
#========================================

# The files in this directory were manually copied from the QHY SDK directories
# for Linux.

LIB_INSTALLS_Linux += ../os/linux-x86_64/libqhyccd.so.24.1.9.12
LIB_INSTALLS_Linux += ../os/linux-x86_64/libqhyccd.so.20
LIB_INSTALLS_Linux += ../os/linux-x86_64/libqhyccd.so


#==============================
include $(TOP)/configure/RULES